### PR TITLE
Update universal payload ID

### PR DESCRIPTION
**Pull request by gdong1**
Update the universal payload ID to align with
the universal payload specification.

Signed-off-by: Guo Dong <guo.dong@intel.com>

### CODE REVIEW

**Review by kvparikh89 — APPROVED** [review]

**Comment by bejeanmo** [comment]
@gdong1 will there be a corresponding PR in the uefi payload repo match this?

**Comment by gdong1** [comment]
> here be a corresponding PR in the uefi payload repo match thi

The open source EDK2 code already made this change. the internal UEFI payload would rebase edk2 master.

**Comment by kvparikh89** [comment]
@gdong1: Does this affect the branch that we use 202008?

**Comment by gdong1** [comment]
> s this affect the branch that we use 20200
no impact.

**Comment by gdong1** [comment]
the qume test failure was caused by the test case which used a pre-built UEFI payload and it is outdated.
The test case should be updated separately.

**Pull request merged**
