### PR TITLE
fix: [Common] Fix Coverity issues

### PR DESCRIPTION
**Pull request by tsaikevin**
Checked for Null pointer before dereference (CWE 476)

### CODE REVIEW

**Comment by bejeanmo** [comment]
@tsaikevin is an ASSERT good enough to cover this? We have DEBUG_PROPERTY_DEBUG_ASSERT_ENABLED set in PcdDebugPropertyMask even in release mode, but that may not be the case in a non-default use case. I think it's better to return an error status in this case also.

**Comment by tsaikevin** [comment]
> @tsaikevin is an ASSERT good enough to cover this? We have DEBUG_PROPERTY_DEBUG_ASSERT_ENABLED set in PcdDebugPropertyMask even in release mode, but that may not be the case in a non-default use case. I think it's better to return an error status in this case also.

@bejeanmo update the code with error status returning to caller. pls review it.

Either way should work, as long as avoiding pointer dereference. fyi

**Review by bejeanmo — CHANGES_REQUESTED** [review]
Update copyright dates. Otherwise looks good.

**Review by gdong1 — APPROVED** [review]

**Comment by tsaikevin** [comment]
> Update copyright dates. Otherwise looks good.

@bejeanmo done. fyi

**Pull request merged**
