### PR TITLE
ICXD: Fix R_CDF_PCH_GPIO_PCR_GPP_N_PADCFGLOCKTX register offset

### PR DESCRIPTION
**Pull request by buytenh**
Signed-off-by: Lennert Buytenhek <buytenh@arista.com>

### CODE REVIEW

**Comment by cshur** [comment]
There are two PADCFGLOCKTX registers. (TxState Register)
PADCFGLOCKTX_WEST2_0 is C4h, PADCFGLOCKTX_WEST1_0 is D4h. GPIO table refer C4h register.
No need to update this code.

**Comment by buytenh** [comment]
This about the EAST side GPIO registers, not the WEST side.

There is indeed a PADCFGLOCKTX register at offset 0xc4, but that is
the PADCFGLOCKTX register for the EAST2 (L bank), while the PADCFGLOCKTX
register for the EAST0 (N bank) is at 0xd4.

**Review by cshur — APPROVED** [review]
Looks good to me.

**Comment by cshur** [comment]
I checked with BIOS and yes. You are right.

**Pull request merged**
