### PR TITLE
Extend SBL build process to build individual component

### PR DESCRIPTION
**Pull request by mauricema**
Current SBL build script can only be used to build SBL image.
It would be helpful if it can be extended to support build individual
DSC component, such as some other standalone payload. This patch
introduced a new subcommand "build_dsc" to enable this capability.

Signed-off-by: Maurice Ma <maurice.ma@intel.com>

### CODE REVIEW

**Comment by myguitar** [comment]
Do we have a .dsc we can test on the latest code base?

**Comment by mauricema** [comment]
We don't have any existing payload DSC in the repo.  But I think we can add a helloworld DSC to show how to build a dummy payload using this method.

**Comment by mauricema** [comment]
Added the following PR to show an example on how to use it to build a payload binary.
https://github.com/slimbootloader/slimbootloader/pull/813

**Comment by myguitar** [comment]
The rebuild_basetools() needs to be added in build_dsc while testing #813 .

**Comment by mauricema** [comment]
ok, let me take a look.

**Comment by mauricema** [comment]
Yes, you are right.  Added the missing base tool build in new commit.

**Pull request merged**
