### PR TITLE
Add build support for PseFw image

### PR DESCRIPTION
**Pull request by bteo1**
Integrate Pse firmware into Slimboot.

Change-Id: I89875cd9ef03d38027e7ead6206661522d0bd273
Signed-off-by: Teo, Boon Tiong <boon.tiong.teo@intel.com>

### CODE REVIEW

**Comment by jgutbub** [comment]
The changes look good, the only thing I'm wondering about is if the this FW binary is included in Stage2 if we want to do FWU it will require updating all of Stage2. Any thoughts anyone has on that?

**Comment by mauricema** [comment]
James has a good point.  The IP FW should be able to be updated separately.   So it should not be part of the Stage2.  Instead, it needs a new region for that so that it can be authenticated and updated independly of SBL Stages and Payloads.

**Comment by bteo1** [comment]
Thank for  the feedback. And yes, we can bring it back for further discussion.

**Comment by bteo1** [comment]
Need to re-architect the implementation.

**Pull request closed without merging**
