### PR TITLE
Add SBL logos for community usage

### PR DESCRIPTION
**Pull request by jgutbub**
Slim Bootloader has its own set of approved logos. Add them to
the repo for community usage along with guidelines on logo usage.

Signed-off-by: James Gutbub <james.gutbub@intel.com>

### CODE REVIEW

**Comment by jgutbub** [comment]
> Can we put the logo into Platform\CommonBoardPkg\Logo instead of root directory ?

Sure, fixed in latest commit.

**Comment by mauricema** [comment]
Also there is a logo.bmp under BootlaoderCorePkg.  Do we need to move that one as well ?

**Comment by jgutbub** [comment]
> Also there is a logo.bmp under BootlaoderCorePkg. Do we need to move that one as well ?

We can move it, logo.bmp is being used for splash screen. The new logo files being uploaded are JPEG format so aren't for splash screen without converting to BMP format. Do we want to move logo.bmp?

**Comment by mauricema** [comment]
I think it might be better to have all logo in a single place.

**Comment by jgutbub** [comment]
> I think it might be better to have all logo in a single place.

Moved in latest push and updated FDF logo.bmp path.

**Comment by mauricema** [comment]
Looks good to me.

**Pull request merged**
