### PR TITLE
IPC and SideBand Interfaces - Adding IPC/Sideband

### PR DESCRIPTION
**Pull request by andreyv1978**
- Created BaseIpcLib
- Sideband Interface picked from
tianocore/edk2-platforms
branch: devel-IntelAtomProcessorE3900
commit: 181f9e6c6ccde6e3fa62278b3a8b39cfb5844a7c
- IPC Interface picked from
tianocore/edk2-platforms
branch: devel-IntelAtomProcessorE3900
commit: 181f9e6c6ccde6e3fa62278b3a8b39cfb5844a7c
- Updated Stage1BBoardInitLib.C with a test function

Signed-off-by: Andrey Vinokurtsev <avinok@gmail.com>

### CODE REVIEW

**Comment by andreyv1978** [comment]
Can someone help how can i squash all changesets to one single on the remote here ? 
I can create a new branch with a single changeset, but the history would be lost. How can I keep the history of reviews?
I've used Mercurial and svn with the review board, it was much easier, but for git I need a tricks to learn :)

**Comment by mauricema** [comment]
We can squash them at merge time.   Or if you want to do it locally on your branch, you will need to use "git rebase" and them pick the ones to be squashed.  
Google it, and this link seems to be pretty good on how to do it in git.
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by mauricema** [comment]
The travis CI check failed.  It reported EOL issues.  Please fix it.

hecking git commit: master..08b4cd0aa7ab997e4e1a2de2e33c8ad3b7783fac
The commit message format passed all checks.
Code format is not valid:
 * Line ending ('\n') is not CRLF
   File: Silicon/ApollolakePkg/Include/Library/SideBandLib.h
   Line: #endif // _SB_LIB_H_
 * Line ending ('\n') is not CRLF
   File: Silicon/ApollolakePkg/Library/BaseIpcLib/BaseIpcLib.inf
   Line:   gEfiMdePkgTokenSpaceGuid.PcdPciExpressBaseAddress

**Comment by andreyv1978** [comment]
> We can squash them at merge time. Or if you want to do it locally on your branch, you will need to use "git rebase" and them pick the ones to be squashed.
> Google it, and this link seems to be pretty good on how to do it in git.
> https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

if you will squash them in the merge time it absolutely good, rebasing it and creating a new branch would destroy the review history

**Comment by mauricema** [comment]
Please address the travis check issue.
It has EOL format issue for some files.   You can run BaseTools\Scripts\PatchCheck.py to check your commit to see if it can pass the precommit check.

Also it has missing Signed-off-by in commit message.
You can use "git commit --amend -s" to add that.

**Comment by mauricema** [comment]
> > We can squash them at merge time. Or if you want to do it locally on your branch, you will need to use "git rebase" and them pick the ones to be squashed.
> > Google it, and this link seems to be pretty good on how to do it in git.
> > https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec
> 
> if you will squash them in the merge time it absolutely good, rebasing it and creating a new branch would destroy the review history

you don't have to create new a branch for that.  git rebase can be done on your current branch without issue.   Anyway,  no worry for the squash for now.

**Comment by andreyv1978** [comment]
> BaseTools\Scripts\PatchCheck.py

the last commit should fix all the remaining problems:

Checking git commit: HEAD
The commit message format passed all checks.
The code passed all checks.

the build is failing on the previous commits, squashing them to a single one should produce a clean patch
'Checking git commit: e9e5c37
The commit message format passed all checks.
The code passed all checks.'

**Comment by mauricema** [comment]
If that is the case, we will have to squash your local commit in order to pass the travis check. 
We cannot merge commit with travis check failure.

**Comment by andreyv1978** [comment]
closed in favor of https://github.com/slimbootloader/slimbootloader/pull/742

**Pull request closed without merging**
