### PR TITLE
Add support for 64bit compiling map file

### PR DESCRIPTION
**Pull request by mauricema**
This patch enhanced the map format parsing for map files generated
by x64 MSFT compiler.

Signed-off-by: Maurice Ma <maurice.ma@intel.com>

### CODE REVIEW

**Comment by myguitar** [comment]
Let me take a look Travis.

**Comment by myguitar** [comment]
It looks there is a failure - https://travis-ci.org/github/slimbootloader/slimbootloader/builds/667807120.
Travis does not post the result.

**Comment by mauricema** [comment]
Thx!  Let me take a look!

**Comment by mauricema** [comment]
Yes, it was GCC map file issue.  Updated the patch to deal with MSFT compiler only at this moment.

**Pull request merged**
