### PR TITLE
TpmLib: Add appropriate safety comparison checks

### PR DESCRIPTION
**Pull request by CunningLearner**
*Safety comparison checks in accordance with TPM2.0 Specification data structures
*Fix comment typos

### CODE REVIEW

**Comment by CunningLearner** [comment]
> do you really need DEBUG_ERROR for every error ? Consider limiting it because it has size impact on final image.

There was only one, still it results in error.
Well, that's too okay, as I believe EFI_D_ERROR is nowhere exercised in our source code - limiting completely!

**Comment by mauricema** [comment]
> > do you really need DEBUG_ERROR for every error ? Consider limiting it because it has size impact on final image.
> 
> There was only one, still it results in error.
> Well, that's too okay, as I believe EFI_D_ERROR is nowhere exercised in our source code - limiting completely!

The newly added code added around 5 "DEBUG ((DEBUG_ERROR, ...)" statements.  In most of the cases, I think error status code should be good enough.  We don't have to print every detailed error string.  SBL is very sensitive to the final code size.

**Comment by CunningLearner** [comment]
> > > do you really need DEBUG_ERROR for every error ? Consider limiting it because it has size impact on final image.
> > 
> > 
> > There was only one, still it results in error.
> > Well, that's too okay, as I believe EFI_D_ERROR is nowhere exercised in our source code - limiting completely!
> 
> The newly added code added around 5 "DEBUG ((DEBUG_ERROR, ...)" statements. In most of the cases, I think error status code should be good enough. We don't have to print every detailed error string. SBL is very sensitive to the final code size.

Yes sure, we can remove every debug statements (all 5). For my knowledge, Is there any verbose mechanism available which can help in such scenarios facilitating both needs?

**Comment by mauricema** [comment]
> > > > do you really need DEBUG_ERROR for every error ? Consider limiting it because it has size impact on final image.
> > > 
> > > 
> > > There was only one, still it results in error.
> > > Well, that's too okay, as I believe EFI_D_ERROR is nowhere exercised in our source code - limiting completely!
> > 
> > 
> > The newly added code added around 5 "DEBUG ((DEBUG_ERROR, ...)" statements. In most of the cases, I think error status code should be good enough. We don't have to print every detailed error string. SBL is very sensitive to the final code size.
> 
> Yes sure, we can remove every debug statements (all 5). Consider it done!

BTW,  if you like,  you can also use DEBUG_VERBOSE level. This level of debug will not be built into the final image by default.  But still can be enabled for debug purpose.

**Pull request merged**
