### PR TITLE
[ICXD] Fix stitching process by getting rid of SblOpen remnants

### PR DESCRIPTION
**Pull request by buytenh**
Signed-off-by: Lennert Buytenhek <buytenh@arista.com>

### CODE REVIEW

**Comment by cshur** [comment]
Stitch script file is for Internal repo. Not for external. Could you explain why we need this change?

**Comment by buytenh** [comment]
Hello,

Thank you for having a look at my proposed change.

With this change, I am able to stitch an ICXD IFWI image using the
StitchIfwi.py script, while without this change, I either need a
top-level build tree symlink from "SblOpen" to the Slim Bootloader
source tree directory or I get the following stitching error:

```
$ make
python Platform/IdavilleBoardPkg/Script/StitchIfwi.py -c Platform/IdavilleBoardPkg/Script/StitchIfwiConfig.py -k SblKeys -s Outputs/idvh/Stitch_Components.zip -w workdir -p MC -b vm -o pdr:pdr_region.bin
Traceback (most recent call last):
  File "/home/buytenh/slimbootloader/Platform/IdavilleBoardPkg/Script/BtGUtility.py", line 32, in <module>
    from   IfwiUtility import *
ModuleNotFoundError: No module named 'IfwiUtility'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buytenh/slimbootloader/Platform/IdavilleBoardPkg/Script/StitchIfwi.py", line 23, in <module>
    from   BtGUtility  import *
  File "/home/buytenh/slimbootloader/Platform/IdavilleBoardPkg/Script/BtGUtility.py", line 36, in <module>
    raise  ImportError(err_msg)
ImportError: Cannot find IfwiUtility module!
Please make sure 'SBL_SOURCE' environment variable is set to open source SBL root folder.
make: *** [Makefile:5: sbl_idvh.bin] Error 1
$
```


With this change it works fine:

```
$ make
[...]

Program terminated.
-------------------

IFWI Stitching completed successfully !
Boot Guard Profile: VM
Additional Options: {'pdr': 'pdr_region.bin'}
IFWI image: sbl_idvh.bin

$
```


My change makes ICXD follow the logic used by every other platform in
the external Slim Bootloader repository:

```
$ git grep sblopen_dir | grep abspath
Platform/AlderlakeBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/AlderlakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/ApollolakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CoffeelakeBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CoffeelakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CometlakeBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CometlakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CometlakevBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/CometlakevBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/ElkhartlakeBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/ElkhartlakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/IdavilleBoardPkg/Script/BtGUtility.py:sblopen_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), '../../../../', 'SblOpen')
Platform/IdavilleBoardPkg/Script/BtGUtility.py:        sblopen_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), '../../../../', 'SblOpen')
Platform/IdavilleBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), '../../../../', 'SblOpen')
Platform/IdavilleBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), '../../../../', 'SblOpen')
Platform/TigerlakeBoardPkg/Script/StitchIfwi.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
Platform/TigerlakeBoardPkg/Script/StitchLoader.py:sblopen_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../'))
$
```


Kind regards,
Lennert

**Comment by cshur** [comment]
Yes, if we use openstream directory, there is build issue.  Stitch script file is for FIWI to support validation. Let me find the way if there is any way to meet for upstream and  internal usage. Thanks.

**Review by cshur — APPROVED** [review]
build is OK for both internal and external.

**Pull request merged**
