### PR TITLE
Use LF line endings in the repository

### PR DESCRIPTION
**Pull request by mikecrowe**
Convert the line endings stored for all text files in the repository to
LF. The majority previously used DOS-style CRLF line endings. Add a
.gitattributes file to enforce this and treat certain extensions as
never being text files.

This has implications depending on the client platform you are using the
repository from:

* Windows

The usual configuration for Git on Windows means that text files will
be checked out to the work tree with DOS-style CRLF line endings. If
that's not the case then you can configure Git to do so for the entire
machine with:

 git config --global core.autocrlf true

or for just the repository with:

 git config core.autocrlf true

Line endings will be normalised to LF when they are committed to the
repository. If you commit a text file with only LF line endings then it
will be converted to CRLF line endings in your work tree.

* Linux, MacOS and other Unices

The usual configuration for Git on such platforms is to check files out
of the repository with LF line endings. This is probably the right thing
for you. In the unlikely even that you are using Git on Unix but editing
or compiling on Windows for some reason then you may need to tweak your
configuration to force the use of CRLF line endings as described above.

* General

For more information see
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings .

Fixes: https://github.com/slimbootloader/slimbootloader/issues/1400

### CODE REVIEW

**Comment by mikecrowe** [comment]
The check failures appear to be due to all the files that already existed in the repository that do not pass `PatchCheck.py`. Although I changed that script as part of this commit to require LF line endings, that isn't enough to stop it complaining about all the pre-existing problems.

**Comment by gdong1** [comment]
> The check failures appear to be due to all the files that already existed in the repository that do not pass `PatchCheck.py`. Although I changed that script as part of this commit to require LF line endings, that isn't enough to stop it complaining about all the pre-existing problems.

Yes, the failures mainly caused by existing coding style issues (* Tab character used, Trailing whitespace found). These issues could be fixed separately.

**Comment by mikecrowe** [comment]
> Yes, the failures mainly caused by existing coding style issues (* Tab character used, Trailing whitespace found). These issues could be fixed separately.

At least some of the complaints appeared to be in imported code, so I was wary of modifying the files. Also, some of the tab complaints are for makefiles which are required to contain tab characters. :( Nevertheless, I agree that these issues should be addresses separately.

**Comment by mauricema** [comment]
let me take a look to see if I can get it fixed.

**Comment by mikecrowe** [comment]
Line 48 of the commit message is the URL. In other projects I've contributed to the commit line length rule has not been applied for lines that have a reason to be too long. In this case, I can't make the line shorter without breaking the URL. Using a URL shortner would risk the URL no longer being valid in the future. Should I just remove the URL?

I've added your patch as two separate commits. I'm not sure whether the CI pipeline will like it that way, but it's worth a try.

**Comment by mauricema** [comment]
> Line 48 of the commit message is the URL. In other projects I've contributed to the commit line length rule has not been applied for lines that have a reason to be too long. In this case, I can't make the line shorter without breaking the URL. Using a URL shortner would risk the URL no longer being valid in the future. Should I just remove the URL?
> 
> I've added your patch as two separate commits. I'm not sure whether the CI pipeline will like it that way, but it's worth a try.

Sure.  I am fine with not breaking the URL line.

**Comment by mauricema** [comment]
Looks like separate commit in patch set will not make the patch checker happy since it checks for each patch separately.
At this moment, I would think we just force push this change given the facts that all builds passed and we know the checker will pass after all commits are merged in.

**Comment by mikecrowe** [comment]
> Looks like separate commit in patch set will not make the patch checker happy since it checks for each patch separately.
At this moment, I would think we just force push this change given the facts that all builds passed and we know the checker will pass after all commits are merged in.

If you're happy to do that then so am I. However, I set you as the author of the two commits from your patch and didn't feel able to add Signed-off-by lines in your name. You might want to reword them too since my description was rather inadequate.

Thanks.

**Review by mauricema — APPROVED** [review]
Thanks for the PR changes pf the file EOL style.  :)
Looks good to me.  It has known PatchChecker failure as discussed.
Since it can be addressed by other commits in the patch set,  
we plan to merge this in.

**Comment by mauricema** [comment]
BTW, for the other 2 patches I might want to need to add "Signed off" in commit msg.

**Comment by mauricema** [comment]
Or we can handle them totally separately through different patches. 
You only submit your first patch, and in this way I can rework on the patches under my name.

**Comment by mikecrowe** [comment]
> You only submit your first patch, and in this way I can rework on the patches under my name.

OK. I'll remove your two patches from this PR.

**Comment by mauricema** [comment]
> > You only submit your first patch, and in this way I can rework on the patches under my name.
> 
> OK. I'll remove your two patches from this PR.

Great, thank you so much!  Sorry to make you go back and forth.

**Comment by mauricema** [comment]
Force push this commit per previous discussions.

**Comment by mikecrowe** [comment]
Thanks for landing this. It will be of great help to us. The messing about was mostly my fault for trying to keep the changes separate.

**Comment by mauricema** [comment]
No problem at all.  It was merged.  And I have submitted remaining patches.
Thanks for contributing to SBL project!  😃

**Pull request merged**
