### PR TITLE
feat: copying actm binary to build folder

### PR DESCRIPTION
**Pull request by aborwank**
For platforms with seperate actm binary added code to copy actm binary in build folder

### CODE REVIEW

**Review by lsubash — COMMENTED** [review]
Which component will load ACTM binary?
Can this be added as container IPFW if this can be loaded FSP?

**Comment by aborwank** [comment]
> Which component will load ACTM binary? Can this be added as container IPFW if this can be loaded FSP?

fsp will load ACTM. ACTM binary address has to be given to fsp. It has to be 256K aligned. On adding it in IPFW container some header bits are getting added and hence the alignment becomes wrong.

**Comment by lsubash** [comment]
A

> > Which component will load ACTM binary? Can this be added as container IPFW if this can be loaded FSP?
> 
> fsp will load ACTM. ACTM binary address has to be given to fsp. It has to be 256K aligned. On adding it in IPFW container some header bits are getting added and hence the alignment becomes wrong.

Would you dump first 256 bytes and check with actual binary? With container, ACTM will be a container component and respective component has to be extracted.

**Review by cshur — APPROVED** [review]
LKGM

**Pull request merged**
