### PR TITLE
GpioLib header clean-up

### PR DESCRIPTION
**Pull request by stalamudupula**
Inconsistent and redundant header files are removed.
All projects going forward

 - Use API declared in GpioLib.h
 - Provide instance of GpioSiLib.h
 - Use common defines in GpioConfig.h

[QEMU][APL][CFL][CML][CMLV]
 - Follow above header model
 - Have own instance of GpioLib

[EHL][TGL]
 - Follow above header model
 - Use common GpioLib instance

Signed-off-by: Talamudupula <stalamudupula@gmail.com>

### CODE REVIEW

**Comment by mauricema** [comment]
It is lots of changes.  It might be better later on to break it down into smaller commits.

**Review by mauricema — APPROVED** [review]
Looks good to me.

**Comment by stalamudupula** [comment]
GpioLibInternal.h is separately created from GpioLib.h , to keep functions local to Common GpioLib and not necessarily needed to be exposed as API.

**Comment by gdong1** [comment]
> It is lots of changes. It might be better later on to break it down into smaller commits.

Agree with Maurice. For such big change, had better to have one commit per platform and you could send out all the commits in one patch.  Anyway, you could do it next time.

**Review by gdong1 — APPROVED** [review]

**Pull request merged**
