### PR TITLE
feat: [AZB] Add Arizona Beach platform support

### PR DESCRIPTION
**Pull request by arghyabi**
This patch adds platform and silicon for Arizona Beach (AZB) platform.

TEST=LPDDR5 AZB CRB board is able to boot to Yocto.

### CODE REVIEW

**Comment by arghyabi** [comment]
Triggering CI

**Comment by arghyabi** [comment]
Trigger CI

**Comment by sindhuragrandhi** [comment]
Instead of many #ifdefs in FSPM and FSPS, could you create separate libraries for these two and link them in your BoardConfig?

Like FspsUpdUpdateLibAzb.inf and FspmUpdUpdateLibAzb.inf'

**Comment by arghyabi** [comment]
@randylintw @sindhuragrandhi I removed all the changes from FspmUpdUpdateLib.c and FspsUpdUpdateLib.c and added new files like FspmUpdUpdateLibAzb.c , FspsUpdUpdateLibAzb.c , FspmUpdUpdateLibAzb.inf and FspsUpdUpdateLibAzb.inf and keep only the platform-specific codes.

**Review by sindhuragrandhi — APPROVED** [review]

**Review by gdong1 — APPROVED** [review]

**Pull request merged**
